# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tai's home
author: "Tai Le Tien"
description: > # this means to ignore newlines until "baseurl:"
    Tai's home page.
baseurl: ""   # the subpath of your site, e.g. /blog
url: "https://letientai299.github.io" # the base hostname & protocol for your site
num-recent-post: 10


# Build settings
markdown: kramdown

defaults:
    -
      scope:
        path: ""
      values:
        comments: true

social-icons:
    - title: GitHub
      url: https://github.com/letientai299
      class: github
    - title: Twitter
      url: https://twitter.com/letientai299
      class: twitter
    - title: LinkedIn
      url: https://www.linkedin.com/in/letientai299
      class: linkedin
