title: Tai LT
author: "Tai Le Tien"
description: "Coding monkey"
baseurl: ""
url: "http://letientai299.github.io"

num-recent-post: 10
num-words-post-title-truncate: 4

future: true

markdown: kramdown

defaults:
  scope:
    path: ""
    values:
      comments: false

social-icons:
  - title: GitHub
    url: https://github.com/letientai299
    class: github
  - title: HackerRank
    url: https://hackerrank.com/letientai299
    class: hackerrank
  - title: Twitter
    url: https://twitter.com/letientai299
    class: twitter
  - title: LinkedIn
    url: https://www.linkedin.com/in/letientai299
    class: linkedin

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  startings: [html, head, body]

gems:
  - jekyll-seo-tag
