# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tai LT
author: "Tai Le Tien"
description: > # this means to ignore newlines until "baseurl:"
    Tai's blog.
baseurl: ""
url: "http://letientai299.github.io"

num-recent-post: 10
num-words-post-title-truncate: 4

future: true

# Build settings
markdown: kramdown

defaults:
    -
      scope:
        path: ""
      values:
        comments: true

social-icons:
    - title: GitHub
      url: https://github.com/letientai299
      class: github
    - title: HackerRank
      url: https://hackerrank.com/letientai299
      class: hackerrank
    - title: Twitter
      url: https://twitter.com/letientai299
      class: twitter
    - title: LinkedIn
      url: https://www.linkedin.com/in/letientai299
      class: linkedin

sass:
  style: compressed
