title: Tai Le
author: "Tai Le"
description: "Wannabe Hacker"
baseurl: ""
url: "https://letientai.io"

num-recent-post: 10
num-words-post-title-truncate: 4

future: true

markdown: kramdown

defaults:
  scope:
    path: ""
    values:
      comments: false

social-icons:
  - title: GitHub
    url: https://github.com/letientai299
    class: github
  - title: LinkedIn
    url: https://www.linkedin.com/in/letientai299
    class: linkedin

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  startings: [html, head, body]


# SEO
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  name: Tai Le Tien
  links:
    - https://www.linkedin.com/in/letientai299
    - https://github.com/letientai299
